// <auto-generated />
using System;
using Common.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Common.Storage.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.Chat.ChatMessage", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<long>("OrderKey")
                        .HasColumnType("bigint")
                        .HasColumnName("order_key");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("SenderDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_display_name");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_user_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("RoomId", "OrderKey");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("messages_sent_at_idx");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Common.Rooms.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("RoomId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Common.Storage.RoomBan", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("RoomId", "UserId");

                    b.ToTable("room_bans", (string)null);
                });

            modelBuilder.Entity("Common.Chat.ChatMessage", b =>
                {
                    b.HasOne("Common.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Storage.RoomBan", b =>
                {
                    b.HasOne("Common.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
