#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

ARG BuildConfiguration=Release

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
ARG BuildConfiguration
WORKDIR /src
COPY ["nuget.config", "."]
COPY ["RoomServer/RoomServer.csproj", "RoomServer/"]
COPY ["Common/Common.csproj", "Common/"]
RUN dotnet restore "RoomServer/RoomServer.csproj"
COPY . .
WORKDIR "/src/RoomServer"
RUN dotnet build "RoomServer.csproj" -c ${BuildConfiguration} -o /app/build

FROM build AS publish
ARG BuildConfiguration
RUN dotnet publish "RoomServer.csproj" -c ${BuildConfiguration} -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RoomServer.dll"]