#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
ENV BuildConfiguration=Release
WORKDIR /src
COPY ["nuget.config", "."]
COPY ["ChatConnector/ChatConnector.csproj", "ChatConnector/"]
COPY ["Common/Common.csproj", "Common/"]
RUN dotnet restore "ChatConnector/ChatConnector.csproj"
COPY . .
WORKDIR "/src/ChatConnector"
RUN dotnet build "ChatConnector.csproj" -c ${BuildConfiguration} -o /app/build

FROM build AS publish
ENV BuildConfiguration=Release
RUN dotnet publish "ChatConnector.csproj" -c ${BuildConfiguration} -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ChatConnector.dll"]