<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\connection.proto" GrpcServices="None" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Common.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Adaptare" Version="2.2.1" />
    <PackageReference Include="Adaptare.Nats" Version="2.2.1" />
    <PackageReference Include="Google.Protobuf" Version="3.35.1" />
    <PackageReference Include="Grpc.Tools" Version="2.82.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StackExchange.Redis" Version="3.0.17" />
  </ItemGroup>

</Project>
