#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
ENV BuildConfiguration=Release
WORKDIR /src
COPY ["nuget.config", "."]
COPY ["ChatServer/ChatServer.csproj", "ChatServer/"]
COPY ["Common/Common.csproj", "Common/"]
RUN dotnet restore "ChatServer/ChatServer.csproj"
COPY . .
WORKDIR "/src/ChatServer"
RUN dotnet build "ChatServer.csproj" -c ${BuildConfiguration} -o /app/build

FROM build AS publish
ENV BuildConfiguration=Release
RUN dotnet publish "ChatServer.csproj" -c ${BuildConfiguration} -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ChatServer.dll"]